// src/routes/contact/+page.svelte
<svelte:head>
  <title>cyber5 — The Cybersecurity Club of CRHS</title>
</svelte:head>

<header>
  <h1>contact</h1>
</header>

<p>Join our <a href="https://matrix.to/#/!OAvvLnxtvgCioPvRTp:projectsegfau.lt?via=projectsegfau.lt">Matrix</a> if you want a quick response from us. You should join anyways ;)</p>

<p>You can also contact us through our email at <a href="mailto:sudoers@cyber5.club">sudoers@cyber5.club</a></p>

<p>You can encrypt your email with our <a href="/pubkey.asc">PGP key</a></p>

// pages/contact.tsx
import { ReactNode } from 'react';

import { Text, Flex, Spacer } from '@chakra-ui/react';

import Link from 'next/link';

import styles from '@/styles/Contact.module.scss';
import Footer from '@/components/Footer';

interface Props {
  children: ReactNode;
}

function Red(props: Props) {
  return <span style={{ color: '#FF002A' }}>{props.children}</span>;
}

function RedUnderline(props: Props) {
  return <u style={{ textDecorationColor: '#FF002A' }}>{props.children}</u>;
}

function Header() {
  return (
    <header className={styles.header}>
      <Flex minWidth='100%'>
        <Text as='b' fontSize='4xl'>
          Contact
        </Text>
        <Spacer />
      </Flex>
      <Spacer />
      <Text fontSize='lg'>
        You can email us at{' '}
        <Link href='mailto:sudoers@cyber5.club'>
          <RedUnderline>
            <Red>sudoers@cyber5.club</Red>
          </RedUnderline>
        </Link>
        <br />
        <br />
        Encrypt your email using our{' '}
        <Link href='/pubkey.asc'>
          <RedUnderline>
            <Red>PGP key</Red>
          </RedUnderline>
        </Link>
        <br />
        <br />
        Contact us in our{' '}
        <Link href='https://matrix.to/#/!OAvvLnxtvgCioPvRTp:projectsegfau.lt?via=projectsegfau.lt'>
          <RedUnderline>
            <Red>Matrix space</Red>
          </RedUnderline>
        </Link>{' '}
        for a faster response.
      </Text>
    </header>
  );
}

export default function Contact() {
  return (
    <main className={styles.wrapper}>
      <div className={styles.main}>
        <Header />
      </div>
      <Footer />
    </main>
  );
}
